# Generated by Django 3.2.9 on 2022-05-08 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20220508_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionchoice',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.category'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.TextField(blank=True, max_length=79, null=True, verbose_name='Choice'),
        ),
    ]
