# Generated by Django 3.2.9 on 2022-05-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20220508_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'quizes'},
        ),
    ]
