# Generated by Django 3.2.9 on 2022-05-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='selected_answer',
            field=models.IntegerField(default=0, verbose_name='Selected Answer:'),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='answer_position',
            field=models.IntegerField(default=0, verbose_name='Answer Position:'),
        ),
    ]
