# Generated by Django 3.2.9 on 2022-05-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20220508_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'quiz', 'verbose_name_plural': 'quizes'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='display_questions',
            field=models.SmallIntegerField(choices=[(1, 'By question'), (0, 'All in one page')], default=0, verbose_name='Display questions'),
        ),
    ]
