# Generated by Django 3.2.9 on 2022-05-22 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0014_answer_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'Set of answers to quiz', 'verbose_name_plural': 'Sets of answers to quiz'},
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
