# Generated by Django 3.2.9 on 2022-05-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20220522_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='questions.quiz', verbose_name='Quiz'),
        ),
    ]
